version: "2.4"
services:
  app:
    restart: always
    image: registry.cn-wulanchabu.aliyuncs.com/programschool-dev/entry-proxy:latest
    container_name: entry-proxy
    network_mode: bridge
    ports:
      - 2090:2090
      - 80:80
    entrypoint: bash -c "/home/entry-proxy > /home/logs/logs.log 2>&1"
    volumes:
      - /home/ssl:/home/ssl
      - /home/services/entry-proxy/logs:/home/logs
