version: "2.4"
services:
  redis:
    image: 'redis:latest'
    container_name: redis-server
    ports:
      - 6379:6379
    network_mode: bridge
    entrypoint: redis-server --appendonly yes
    restart: always
